# Generated by Django 5.0.4 on 2024-04-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
